plans:
  qa:
      accessTokenUri: qa11
      userAuthorizationUri: qa12
      userInfoUri: qa13
      clientId: qa14
      clientSecret: qa15
  prod:
      accessTokenUri: prod11
      userAuthorizationUri: prod12
      userInfoUri: prod13
      clientId: prod14
      clientSecret: prod55